Chf 45/feed global
VicenteEspinosa/backendChefsitos pull request #31
Opened 2022-06-12 01:07 UTC by cahinostroza

## Descripción General
Se crea la operación para obtener las recetas del feed global

## Detalles
* Agregar nuevos datos para el seed
* Crear el endpoint ` http://localhost:8000/api/recipes/feed/`
* Crear el modelo `like`
* Agregar `likes` al serializer de `recipe`
* Agregar tests para el endpoint creado

## Probar endpoint

* Correr `docker compose run web python manage.py init_base_data`
 para agregar los nuevos datos a la BD
* Iniciar sesión con admin
* GET http://localhost:8000/api/recipes/
* Comprobar que en las recetas no se encuentre ninguna con user_id=1
* GET http://localhost:8000/api/recipes/?order_by=popularity
* Comprobar que el orden es en base al número de likes

## Tarjeta en Jira
[CHF-45](https://tfflores.atlassian.net/browse/CHF-45)

2022-06-12 21:28 UTC, tfflores approved these changes

2022-06-12 21:34 UTC, tfflores requested changes
La funcionalidad del feed global está bien. Sin embargo, la modelación del Like tiene un detalle. Se había decidido que la tabla intermedia Like contaría con un atributo booleano que podía ser Verdadero o Falso, el cual servía para indicar si este era un Like (True) o Dislike (False). Este booleano debería aparecer también en el desglose de los likes de una review en el JSON que retorna el GET del feed global.

2022-06-12 23:18 UTC, cahinostroza commented
@tfflores ahí actualicé, ojo que tienes que correr las migraciones para probar los cambios, aproveché de agregar más datos al seed de rating, para cachar si funcionaba bien el orden por popularidad

2022-06-13 00:13 UTC, tfflores approved these changes

2022-06-13 00:14 UTC, merged