Chf 10/login
VicenteEspinosa/backendChefsitos pull request #6
Opened 2022-05-01 23:15 UTC by cahinostroza

## Breaking Changes
Es necesario volver a correr `docker-compose build` para instalar el nuevo paquete, utilizado para la verificación

## Descripción General
Se crea las operación de login y logout

## Detalles
* Se separan las operaciones de la vista de usuarios
* Se crean las operaciones de login y logout
* Se crea un servicio de validación de los parámetros de las request
* Se manejan los distintos tipos de errores en las operaciones

## Tarjeta en Jira
[CHF-10](https://tfflores.atlassian.net/browse/CHF-10)

2022-05-05 03:26 UTC, VicenteEspinosa commented
El signin no debería generar algún tipo de token? como un JWT o algo para no necesitar la clave al momento de hacer posts?

2022-05-05 15:46 UTC, cahinostroza commented
> 

@VicenteEspinosa no es necesario, porque django maneja las sesiones por detrás, entonces si yo quiero hacer un post y como requisito debe estar loggeado pongo `user.is_authenticated` y era

2022-05-05 17:41 UTC, tfflores requested changes

2022-05-05 17:41 UTC, tfflores commented on recipelib/operations/users/signup.py
> +        user = User.objects.get(username=data.get('username'))
el objects.get lanza una excepción cuando no encuentra el objeto. Para que este bloque de código funcione, se debe ocupar filter:
```user = User.objects.filter(username=data.get('username'))```
En este caso si no encuentra el usuario con el username indicado, la lista `user` estará vacía y por ende el branching seguiría funcionando según lo esperado.

2022-05-05 17:46 UTC, tfflores requested changes

2022-05-05 17:46 UTC, tfflores commented on recipelib/operations/users/signin.py
> +      return JsonResponse(UserSerializer(user).data, safe=False, status=201)
Cambiar status=201 por status=200 para signin

2022-05-05 18:34 UTC, VicenteEspinosa commented on recipelib/operations/users/signup.py
> +        user = User.objects.get(username=data.get('username'))
Con cambiar la linea 32 y 33 por 
`if User.objects.filter(username=data.get('username')).exists():`
Deberia funcionar

2022-05-05 18:39 UTC, VicenteEspinosa commented
En la [documentación de django](https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated) en la parte de is_authenticated dice: 

> Read-only attribute which is always True (as opposed to AnonymousUser.is_authenticated which is always False). This is a way to tell if the user has been authenticated. This does not imply any permissions and doesn’t check if the user is active or has a valid session. Even though normally you will check this attribute on request.user to find out whether it has been populated by the [AuthenticationMiddleware](https://docs.djangoproject.com/en/4.0/ref/middleware/#django.contrib.auth.middleware.AuthenticationMiddleware) (representing the currently logged-in user), you should know this attribute is True for any [User](https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User) instance.


Creo que no se usa eso para ver si la sesión está activa

2022-05-06 02:21 UTC, cahinostroza commented
@VicenteEspinosa lo que yo entiendo es que con el is_authenticated tu tienes que manejar el que no esté loggeado. Prueba y agrega
 ```
if not request.user.is_authenticated:
  return JsonResponse({"internalCode":"no autorizado", "message":"No autorizado"}, safe=False, status=401)
````
antes del try en la función de signout y luego intenta hacer signout sin haber hecho signin, y te va a tirar el error de que no está autorizado

2022-05-06 02:28 UTC, cahinostroza commented on recipelib/operations/users/signup.py
> +        user = User.objects.get(username=data.get('username'))
Ahí lo cambié

2022-05-06 02:28 UTC, cahinostroza commented on recipelib/operations/users/signin.py
> +      return JsonResponse(UserSerializer(user).data, safe=False, status=201)
También cambié el code de signout

2022-05-07 15:46 UTC, VicenteEspinosa approved these changes

2022-05-07 16:04 UTC, merged